# development:
#   bucket: flashingdeals
#   access_key_id: 
#   secret_access_key:
# test:
#   bucket: flashingdeals
#   access_key_id: 
#   secret_access_key:
production:
  bucket: flashingdeals
  access_key_id: <%= ENV["AMAZON_S3_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AMAZON_S3_SECRET_ACCESS_KEY"] %>